name: Sandbox`s CI/CD

on:
  push:
    branches:
      - main

permissions: 
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v7
        
      - name: Buildx sozlash
        uses: docker/setup-buildx-action@v3

      - name: GHCR'ga kirish
        uses: docker/login-action@v3
        with: 
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Teglarni tayyorlash
        id: javoh
        uses: docker/metadata-action@v5
        with: 
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=sha-
            type=raw,value=latest
      
      - name: Build va push
        uses: docker/build-push-action@v6
        with: 
          context: .
          push: true
          tags: ${{ steps.javoh.outputs.tags }}
          labels: ${{ steps.javoh.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max