name: Sandbox`s CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Kodni yuklab olish
        uses: actions/checkout@v7
        
      - name: .NET o'rnatish
        uses: actions/setup-dotnet@v6
        with: 
          dotnet-version: '10.0.x'

      - name: Paketlarni tortish
        uses: dotnet restore

      - name: Build qilish
        uses: dotnet build --no-restore --configuration Release 